use_frameworks!

platform :ios, '9.0'

target 'LMYPersonPeferenceKit_Example' do
  pod 'LMYPersonPeferenceKit', :path => '../'

  target 'LMYPersonPeferenceKit_Tests' do
    inherit! :search_paths

    
  end
end
